import org.mockito.releasetools.example.SomeApi;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library implements SomeApi {

    /**
     * Always return true
     */
    public boolean someLibraryMethod() {
        return 1 == 1;
    }
}
